/**
 * TypeScript 代码生成
 *
 * 生成 TypeScript 类型定义文件 + FFI 客户端类
 */

use quote::quote;
use syn::Type;

use crate::ipc::{MethodInfo, MethodType};

/// 标准化类型字符串：清理空格、统一格式
fn normalize_type(s: &str) -> String {
    s
        .replace(" ,", ",")
        .replace(" , ", ", ")
        .replace(" < ", "<")
        .replace(" <", "<")
        .replace("< ", "<")
        .replace(" > ", ">")
        .replace(" >", ">")
        .replace("> ", ">")
        .trim()
        .to_string()
}

/// Rust 类型到 TypeScript 类型的映射
fn rust_to_ts_type(rust_type: &str) -> String {
    let s = normalize_type(rust_type);

    // Result<T, E> → 提取 T，错误类型由调用方决定
    if let Some(inner) = s.strip_prefix("Result<") {
        if let Some(comma_pos) = inner.rfind(", ") {
            let ok_type = &inner[..comma_pos];
            return rust_to_ts_type(ok_type.trim());
        }
        if let Some(comma_pos) = inner.rfind(',') {
            let ok_type = &inner[..comma_pos];
            return rust_to_ts_type(ok_type.trim());
        }
    }

    // Vec<T> → T[]
    if let Some(inner) = s.strip_prefix("Vec<") {
        if let Some(elem) = inner.strip_suffix('>') {
            return format!("{}[]", rust_to_ts_type(elem.trim()));
        }
    }

    // Option<T> → T | null
    if let Some(inner) = s.strip_prefix("Option<") {
        if let Some(inner_type) = inner.strip_suffix('>') {
            let mapped = rust_to_ts_type(inner_type.trim());
            if mapped == "void" {
                return "null".to_string();
            }
            return format!("{} | null", mapped);
        }
    }

    // 元组 (T1, T2) → [T1, T2] (TS tuple)
    if s.starts_with('(') && s.ends_with(')') {
        let inner = &s[1..s.len()-1];
        let parts: Vec<&str> = inner.split(',')
            .map(|p| p.trim())
            .filter(|p| !p.is_empty())
            .collect();
        if !parts.is_empty() {
            let mapped: Vec<String> = parts.iter()
                .map(|p| rust_to_ts_type(p))
                .collect();
            // 对于 (f64, f64) 这种坐标对，更合适的可能是 { x: f64, y: f64 }
            // 但这里先用 TS tuple 语法
            return format!("[{}]", mapped.join(", "));
        }
    }

    // 基本类型映射
    match s.as_str() {
        "i8" | "i16" | "i32" | "i64" | "i128" | "isize"
        | "u8" | "u16" | "u32" | "u64" | "u128" | "usize"
        | "f32" | "f64" => "number".to_string(),
        "bool" => "boolean".to_string(),
        "String" | "str" | "&str" => "string".to_string(),
        "Vec<u8>" => "Uint8Array".to_string(),
        "()" => "void".to_string(),
        _ => s,
    }
}

/// 将 syn Type 转为字符串（简化版）
fn type_to_string(ty: &Type) -> String {
    let s = quote! { #ty }.to_string();
    normalize_type(&s)
}

/// 驼峰转小驼峰（TS 惯例）
fn to_camel_case(name: &str) -> String {
    let snake = name.trim_start_matches('_');
    let mut result = String::new();
    let mut upper_next = false;

    for (i, ch) in snake.chars().enumerate() {
        if ch == '_' {
            upper_next = true;
        } else if upper_next {
            result.push(ch.to_ascii_uppercase());
            upper_next = false;
        } else if i == 0 {
            result.push(ch.to_ascii_lowercase());
        } else {
            result.push(ch);
        }
    }
    result
}

/// 生成 FFI 客户端类代码（可运行的 TS 实现）
pub fn generate_ts_client(
    methods: &[MethodInfo],
    trait_name: &syn::Ident,
    ffi_names: &[String],
) -> String {
    let trait_str = trait_name.to_string();
    let client_name = format!("{}Client", trait_str.trim_end_matches("API"));
    let mut ts = String::new();

    ts.push_str("// Auto-generated by electrobun-macros\n");
    ts.push_str("// Do not edit manually\n\n");
    ts.push_str("import { join } from \"path\";\n");
    ts.push_str("import { dlopen, FFIType, CString } from \"bun:ffi\";\n");
    ts.push_str("import type { Window, WindowParams, WindowError, AppError, WebViewError, WebViewOptions, WebViewBounds, FileDialogOptions, FileDialogResult, MessageBoxResult, DialogError, TrayOptions, TrayBounds, TrayError, ClipboardError, SessionError, ShortcutError, DisplayInfo, DisplayError, CoreError, WgpuAdapterOpts, WgpuDeviceOpts, WgpuSurfaceOpts, WgpuError, WindowBounds } from \"../api/types\";\n\n");

    // 生成接口定义
    ts.push_str(&format!("export interface {} {{\n", trait_str));
    for (_i, method) in methods.iter().enumerate() {
        let method_name_ts = to_camel_case(&method.name);
        let params_ts: Vec<String> = method.params.iter()
            .map(|(name, ty)| {
                let ts_type = rust_to_ts_type(&type_to_string(ty));
                format!("{}: {}", to_camel_case(name), ts_type)
            })
            .collect();
        let params_str = params_ts.join(", ");
        let return_ts = match &method.return_type {
            Some(ty) => rust_to_ts_type(&type_to_string(ty)),
            None => "void".to_string(),
        };
        let error_ts = match &method.error_type {
            Some(ty) => rust_to_ts_type(&type_to_string(ty)),
            None => "void".to_string(),
        };
        if error_ts != "void" {
            ts.push_str(&format!("  {}({}): {} | {};\n", method_name_ts, params_str, return_ts, error_ts));
        } else {
            ts.push_str(&format!("  {}({}): {};\n", method_name_ts, params_str, return_ts));
        }
    }
    ts.push_str("}\n\n");

    // 生成 FFI 符号定义
    ts.push_str(&format!("// FFI symbols for {}\n", trait_str));
    ts.push_str("const SYMBOLS = {\n");
    ts.push_str("  electrobun_init_core: { args: [], returns: FFIType.bool },\n");
    for ffi_name in ffi_names {
        ts.push_str(&format!("  {}: {{ args: [FFIType.ptr, FFIType.ptr], returns: FFIType.ptr }},\n", ffi_name));
    }
    ts.push_str("} as const;\n\n");

    // 生成客户端类
    ts.push_str(&format!(
        "export class {} {{\n",
        client_name
    ));
    ts.push_str("  private lib: any;\n");
    ts.push_str("  private initialized = false;\n\n");
    ts.push_str("  constructor(dllPath?: string) {\n");
    ts.push_str("    const path = dllPath ?? this.findDll();\n");
    ts.push_str("    this.lib = dlopen(path, SYMBOLS);\n");
    ts.push_str("    this.initialized = true;\n");
    ts.push_str("    // 首次加载时自动初始化 core 实例\n");
    ts.push_str("    try { if (typeof this.lib.symbols.electrobun_init_core === 'function') this.lib.symbols.electrobun_init_core(); } catch {}\n");
    ts.push_str("  }\n\n");

    ts.push_str("  private findDll(): string {\n");
    ts.push_str("    const platform = process.platform;\n");
    ts.push_str("    const suffix = platform === 'win32' ? '.dll' : platform === 'darwin' ? '.dylib' : '.so';\n");
    ts.push_str("    return join(process.execPath, \"..\", `electrobun_core${suffix}`);\n");
    ts.push_str("  }\n\n");

    ts.push_str("  private call<T>(method: string, params: any): T {\n");
    ts.push_str("    const paramsBuf = Buffer.from(JSON.stringify(params), 'utf-8');\n");
    ts.push_str("    const resultPtr = this.lib.symbols[method](paramsBuf, null);\n");
    ts.push_str("    if (!resultPtr) return undefined as T;\n");
    ts.push_str("    try {\n");
    ts.push_str("      const result = new CString(resultPtr as any).toString();\n");
    ts.push_str("      if (!result) return undefined as T;\n");
    ts.push_str("      return JSON.parse(result) as T;\n");
    ts.push_str("    } catch { return undefined as T; }\n");
    ts.push_str("  }\n\n");

    // 生成每个方法
    for (i, method) in methods.iter().enumerate() {
        let method_name_ts = to_camel_case(&method.name);
        let ffi_name = &ffi_names[i];
        let params_ts: Vec<String> = method.params.iter()
            .map(|(name, ty)| {
                let ts_type = rust_to_ts_type(&type_to_string(ty));
                format!("{}: {}", to_camel_case(name), ts_type)
            })
            .collect();
        let params_str = params_ts.join(", ");
        let param_names: Vec<String> = method.params.iter()
            .map(|(name, _)| to_camel_case(name))
            .collect();
        let param_obj = if param_names.is_empty() {
            "{}".to_string()
        } else if param_names.len() == 1 {
            // 单参数直接传值（Rust 侧从 JSON 直接解析为该类型）
            param_names[0].clone()
        } else {
            format!("{{ {} }}", param_names.join(", "))
        };

        let return_ts = match &method.return_type {
            Some(ty) => rust_to_ts_type(&type_to_string(ty)),
            None => "void".to_string(),
        };
        let error_ts = match &method.error_type {
            Some(ty) => rust_to_ts_type(&type_to_string(ty)),
            None => "void".to_string(),
        };

        ts.push_str(&format!("  {}(", method_name_ts));
        ts.push_str(&params_str);
        ts.push_str("): ");
        if error_ts != "void" {
            ts.push_str(&format!("{} | {}", return_ts, error_ts));
        } else {
            ts.push_str(&return_ts);
        }
        ts.push_str(" {\n");
        ts.push_str(&format!("    return this.call<{}>(\"{}\", {});\n", return_ts, ffi_name, param_obj));
        ts.push_str("  }\n\n");
    }

    ts.push_str("}\n");
    ts.push_str(&format!(
        "\nexport const {} = new {}();\n",
        to_camel_case(&trait_str),
        client_name
    ));

    ts
}

/// 生成 TypeScript 类型定义字符串
pub fn generate_typescript_types(
    methods: &[MethodInfo],
    trait_name: &str,
) -> Result<String, String> {
    let mut ts = String::new();

    ts.push_str("// Auto-generated by electrobun-macros\n");
    ts.push_str("// Do not edit manually\n\n");

    let interface_name = trait_name.trim_start_matches("crate::");

    ts.push_str(&format!("export interface {} {{\n", interface_name));

    for method in methods {
        let method_name_ts = to_camel_case(&method.name);

        let params_ts: Vec<String> = method.params.iter()
            .map(|(name, ty)| {
                let ts_type = rust_to_ts_type(&type_to_string(ty));
                format!("{}: {}", to_camel_case(name), ts_type)
            })
            .collect();

        let params_str = params_ts.join(", ");

        match method.method_type {
            MethodType::Stream => {
                ts.push_str(&format!("  // Stream: {}\n", method_name_ts));
                ts.push_str(&format!("  {}_subscribe(callback: (event: any) => void): number;\n", method_name_ts));
                ts.push_str(&format!("  {}_unsubscribe(streamId: number): void;\n", method_name_ts));
            }
            _ => {
                let return_ts = match &method.return_type {
                    Some(ty) => {
                        let rust_ret = type_to_string(ty);
                        if rust_ret == "()" { "void".to_string() } else { rust_to_ts_type(&rust_ret) }
                    }
                    None => "void".to_string(),
                };

                let error_ts = match &method.error_type {
                    Some(ty) => {
                        let rust_err = type_to_string(ty);
                        rust_to_ts_type(&rust_err)
                    }
                    None => "void".to_string(),
                };

                if error_ts != "void" {
                    ts.push_str(&format!("  {}({}): {} | {};\n", method_name_ts, params_str, return_ts, error_ts));
                } else {
                    ts.push_str(&format!("  {}({}): {};\n", method_name_ts, params_str, return_ts));
                }
            }
        }
    }

    ts.push_str("}\n");

    Ok(ts)
}

/// 生成 TS 输出（编译时写入文件）
pub fn generate_ts_output(
    methods: &[MethodInfo],
    trait_name: &syn::Ident,
    ffi_names: &[String],
) -> proc_macro2::TokenStream {
    let trait_str = trait_name.to_string();
    let out_dir = std::env::var("CARGO_MANIFEST_DIR")
        .unwrap_or_else(|_| ".".to_string());
    let api_dir = format!("{}/../../packages/cli/src/core/generated", out_dir);

    // 写 .d.ts 类型声明
    let dts_path = format!("{}/{}.d.ts", api_dir, trait_str);
    match generate_typescript_types(methods, &trait_str) {
        Ok(ts_code) => {
            let _ = std::fs::create_dir_all(&api_dir);
            let _ = std::fs::write(&dts_path, &ts_code);
            eprintln!("[eden_ipc] Generated TS types: {}", dts_path);
        }
        Err(e) => {
            eprintln!("[eden_ipc] Warning: Failed to generate TS types: {}", e);
        }
    }

    // 写 .ts FFI 客户端实现
    let ts_path = format!("{}/{}Client.ts", api_dir, trait_str);
    let ts_code = generate_ts_client(methods, trait_name, ffi_names);
    let _ = std::fs::write(&ts_path, &ts_code);
    eprintln!("[eden_ipc] Generated TS client: {}", ts_path);

    quote! {
        // TypeScript 类型和客户端已生成
    }
}
